name: Build Server

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: macos-15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Swift
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: "6.2.0"

      - name: Setup Swift static SDK
        run: |
          swift sdk install https://download.swift.org/swift-6.2-release/static-sdk/swift-6.2-RELEASE/swift-6.2-RELEASE_static-linux-0.0.1.artifactbundle.tar.gz \
            --checksum d2225840e592389ca517bbf71652f7003dbf45ac35d1e57d98b9250368769378
            
      - name: Build release
        run: |
          cd core-cloud-server
          swift build -c release \
            --swift-sdk x86_64-swift-linux-musl \
            -Xswiftc -cross-module-optimization 
            
      - name: Create artifacts
        run: |
          mkdir result
          mv core-cloud-server/.build/release/CoreCloudServer result/CoreCloudServer_release

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: CoreCloudServer
          path: result
          
